#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""build_pending.py - WIRE HT-31 (paste 143 S6.18): ONE SQL ACT, FOREVER.

    python tools/sql/build_pending.py            writes ht_pending.sql + ht_pending_rollback.sql
    python tools/sql/build_pending.py --check    exit 1 if either file is out of date

EVERY BUILD IS SCHEMA-CHECKED FIRST (paste 148 N10). Every table.column the stack references is diffed
against `schema_snapshot.json` (the live column list) by `schema_check.py`; a miss REFUSES the build -
nothing is written, exit 2, the column is named. 2026-09-23 10:52 is why: `circles.owner` reached the
live database, which has `owner_id`, after eight days of review that could not see it.

WHY THIS EXISTS. Cory's list of things only he can do has carried "paste the SQL" since HT-29, and
every wire that needs a column adds another file to it. Two files is a list; four is a chore nobody
does, and until it is done the app shows quiet lines where features should be. So the wires stack
into ONE file: he pastes `ht_pending.sql` whenever he likes and gets everything that is waiting, in
order, idempotent, whether that is one migration or six.

IT IS GENERATED, AND IT IS COMMITTED (131 Ruling 1: a generator commits what it generates). Adding a
migration means adding one line to `ORDER` below and re-running this - never hand-editing the output,
which would drift from the files it is made of the first time anyone was in a hurry.

REFUSES RATHER THAN HALF-APPLYING. The preamble reads `relrowsecurity` for every table the stack
touches and raises before the first statement if any of them has row level security OFF - because a
policy added to an unprotected table reads as protection and is not (this is 2026-09-15_ht29.sql's own
rule, hoisted to the front so it guards all three files instead of the one that wrote it).
"""
import argparse, io, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))

# In order. A new migration goes at the END: they are applied the way they were written.
ORDER = ['2026-09-15_ht29.sql', '2026-09-20_ht30.sql', '2026-09-22_ht31.sql', '2026-09-23_ht32.sql']
ROLLBACK = ['2026-09-15_ht29_rollback.sql']

# Every table the stack touches. RLS OFF on any of them stops the whole paste.
GUARDED = ['days', 'day_private', 'habits', 'profiles', 'profile_private', 'circles', 'circle_members']

HEAD = """-- ht_pending.sql - EVERYTHING THE TRACKER IS WAITING FOR, IN ONE PASTE.
-- GENERATED by tools/sql/build_pending.py from %s. Never hand-edited: re-run the builder.
--
-- HOW TO RUN: `python tools/sql/apply_pending.py` (paste 148 NUDGE N7). It needs BEV/HT_SUPABASE_DB_URL
-- in Windows Credential Manager and nothing else. The dashboard route still works if you want it:
-- Supabase -> SQL Editor -> New query -> paste this whole file -> Run.
-- Safe to run twice: a second run changes nothing. Undo is ht_pending_rollback.sql beside this file.
--
-- It is %d migration(s), applied in the order they were written, each in its own transaction. If one
-- of them fails, the ones before it stay applied and the ones after it do not run - which is why they
-- are each written to be safe to run again.
--
-- IT REFUSES RATHER THAN HALF-APPLYING. The block below reads row level security for every table this
-- stack touches and stops before the first statement if any of them has it OFF. A policy added to an
-- unprotected table reads as protection and is not.

do $ht_pending$
declare
  bad  text;
  miss text;
begin
  -- A TABLE THAT IS NOT THERE CONTRIBUTES NO ROW, and a guard that reads "no rows with RLS off" would
  -- therefore pass in silence for exactly the table it cannot see - a rename, a wrong schema, or one
  -- character wrong in the builder's own list. So the list is checked for PRESENCE first: what is
  -- missing is named, and nothing is applied. (Found by a review of this wire's diff, not by a test.)
  select string_agg(t, ', ' order by t) into miss
    from unnest(array[%s]) as t
   where not exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
                      where n.nspname = 'public' and c.relname = t);
  if miss is not null then
    raise exception 'REFUSING: this file guards tables that do not exist in schema public: %%. Nothing '
                    'was applied. Either the database is not the one this stack was written for, or '
                    'tools/sql/build_pending.py names a table wrongly.', miss;
  end if;

  select string_agg(c.relname, ', ' order by c.relname) into bad
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and c.relname in (%s)
     and c.relrowsecurity = false;
  if bad is not null then
    raise exception 'REFUSING: row level security is OFF on %%. Nothing was applied. Switch it on for '
                    'those tables (their owners keep full access) and run this file again.', bad;
  end if;
end
$ht_pending$;

"""

FOOT = """
-- ------------------------------------------------------------------------------------------------
-- DONE. Everything above is applied. The app notices on its next load; nothing needs a deploy.
"""

RB_HEAD = """-- ht_pending_rollback.sql - the undo for ht_pending.sql, in REVERSE order.
-- GENERATED by tools/sql/build_pending.py. Never hand-edited: re-run the builder.
--
-- Each migration's own undo is reproduced here, newest first, because undoing a stack in the order it
-- was applied would drop a column another one still depends on. Run the whole file, or lift out the
-- one block you want - each is complete on its own.
"""


def read(name):
    return io.open(os.path.join(HERE, name), encoding='utf-8').read()


def undo_of(name):
    """The commented UNDO block a migration carries at its foot, un-commented. A migration with no UNDO
    block is named as such rather than skipped silently."""
    src = read(name)
    i = src.find('-- ---- UNDO')
    if i < 0:
        return '-- %s carries no UNDO block of its own.\n' % name
    out = []
    for ln in src[i:].splitlines()[1:]:
        t = ln.strip()
        if t.startswith('--   '):
            out.append(t[5:])
        elif t.startswith('--'):
            out.append(ln.rstrip())
    return '\n'.join(out) + '\n'


def build():
    quoted = ', '.join("'%s'" % t for t in GUARDED)
    body = [HEAD % (', '.join(ORDER), len(ORDER), quoted, quoted)]
    for name in ORDER:
        body.append('\n-- ============================================================================\n'
                    '-- %s\n'
                    '-- ============================================================================\n' % name)
        body.append(read(name))
    body.append(FOOT)
    rb = [RB_HEAD]
    for name in reversed(ORDER):
        rb.append('\n-- ---- undo of %s ----------------------------------------------------------\n' % name)
        rb.append(undo_of(name))
    for name in ROLLBACK:
        rb.append('\n-- ---- %s (its own file, reproduced whole) -------------------\n' % name)
        rb.append(read(name))
    return ''.join(body), ''.join(rb)


def schema_gate():
    sys.path.insert(0, HERE)
    import schema_check
    refs, misses = schema_check.check(''.join(read(n) for n in ORDER), schema_check.load_snapshot())
    for t, c, why in misses:
        print('  MISSING  %s.%s - %s' % (t, c, why))
    print('  schema check %s %d/%d' % ('PASS' if not misses else 'FAIL', len(refs) - len(misses), len(refs)))
    return not misses


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    if not schema_gate():
        print('REFUSED: the stack names a column the live schema does not have. Nothing was written.')
        return 2
    want = {'ht_pending.sql': build()[0], 'ht_pending_rollback.sql': build()[1]}
    drift = []
    for name, text in want.items():
        path = os.path.join(HERE, name)
        have = io.open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if have == text:
            print('  ok      %s (%d bytes)' % (name, len(text)))
            continue
        drift.append(name)
        if a.check:
            print('  DRIFT   %s' % name)
        else:
            io.open(path, 'w', encoding='utf-8', newline='\n').write(text)
            print('  written %s (%d bytes)' % (name, len(text)))
    if a.check and drift:
        print('ht_pending is out of date: %s - run build_pending.py' % ', '.join(drift))
        return 1
    return 0


sys.exit(main())
