-- ht_pending.sql - EVERYTHING THE TRACKER IS WAITING FOR, IN ONE PASTE.
-- GENERATED by tools/sql/build_pending.py from 2026-09-15_ht29.sql, 2026-09-20_ht30.sql, 2026-09-22_ht31.sql, 2026-09-23_ht32.sql. Never hand-edited: re-run the builder.
--
-- HOW TO RUN: `python tools/sql/apply_pending.py` (paste 148 NUDGE N7). It needs BEV/HT_SUPABASE_DB_URL
-- in Windows Credential Manager and nothing else. The dashboard route still works if you want it:
-- Supabase -> SQL Editor -> New query -> paste this whole file -> Run.
-- Safe to run twice: a second run changes nothing. Undo is ht_pending_rollback.sql beside this file.
--
-- It is 4 migration(s), applied in the order they were written, each in its own transaction. If one
-- of them fails, the ones before it stay applied and the ones after it do not run - which is why they
-- are each written to be safe to run again.
--
-- IT REFUSES RATHER THAN HALF-APPLYING. The block below reads row level security for every table this
-- stack touches and stops before the first statement if any of them has it OFF. A policy added to an
-- unprotected table reads as protection and is not.

do $ht_pending$
declare
  bad  text;
  miss text;
begin
  -- A TABLE THAT IS NOT THERE CONTRIBUTES NO ROW, and a guard that reads "no rows with RLS off" would
  -- therefore pass in silence for exactly the table it cannot see - a rename, a wrong schema, or one
  -- character wrong in the builder's own list. So the list is checked for PRESENCE first: what is
  -- missing is named, and nothing is applied. (Found by a review of this wire's diff, not by a test.)
  select string_agg(t, ', ' order by t) into miss
    from unnest(array['days', 'day_private', 'habits', 'profiles', 'profile_private', 'circles', 'circle_members']) as t
   where not exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
                      where n.nspname = 'public' and c.relname = t);
  if miss is not null then
    raise exception 'REFUSING: this file guards tables that do not exist in schema public: %. Nothing '
                    'was applied. Either the database is not the one this stack was written for, or '
                    'tools/sql/build_pending.py names a table wrongly.', miss;
  end if;

  select string_agg(c.relname, ', ' order by c.relname) into bad
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and c.relname in ('days', 'day_private', 'habits', 'profiles', 'profile_private', 'circles', 'circle_members')
     and c.relrowsecurity = false;
  if bad is not null then
    raise exception 'REFUSING: row level security is OFF on %. Nothing was applied. Switch it on for '
                    'those tables (their owners keep full access) and run this file again.', bad;
  end if;
end
$ht_pending$;


-- ============================================================================
-- 2026-09-15_ht29.sql
-- ============================================================================
-- 2026-09-15_ht29.sql - WIRE HT-29 (paste 133): privacy sealed at the table · the group both ways ·
-- a section on every standard · the evening nudge's subscriptions.
--
-- HOW TO RUN (2 minutes). Supabase -> SQL Editor -> New query -> paste this whole file -> Run.
-- ONE transaction: it applies completely or not at all. SAFE TO RUN TWICE: a second run changes nothing.
-- UNDO: 2026-09-15_ht29_rollback.sql (restores the policies this file replaced, from the backup it takes).
-- Proven against a local Postgres with Supabase's roles before it was handed over: tools/sql/test_privacy_pg.py.
--
-- WHAT CHANGES, AND WHAT DOES NOT
--  1 · day_private, profile_private, habits -> OWNER-ONLY in every direction. Every existing policy on
--      these three tables is copied into ht29_policy_backup and then replaced by four owner policies.
--      Nobody's own access changes; any wider policy that may exist is gone. The journal (brain dump ·
--      completed · prayer · the rating's why) can be read by its author and by no one else.
--  2 · habits.section ('morning' | 'night' | 'standards' | 'weekly'). Paste 133 Ruling 3: every standard
--      is placed where it shows TODAY and a person moves it after - weekly -> Weekly, a planned time ->
--      Morning, no time -> Standards; the Sabbath -> Night (paste 133 S2.10). Only rows with no section
--      are placed, so a second run places nothing. Rows are updated, never inserted or deleted: the
--      result grid at the end prints the count before and after.
--  3 · The group, both ways: a member sees every membership row of a circle they are in - the reason two
--      members could not see each other - and can read co-members' names, days and circles.
--      ADDITIVE ONLY on days / profiles / circles / circle_members: no existing policy there is touched.
--      Those four get a co-member SELECT policy and nothing else, so this file REFUSES TO RUN if row level
--      security is off on any of them (switching it on there would block their owners' own writes). It reads
--      the switch first, records it in ht29_rls_backup for the undo, and prints it in the grid at the end.
--  4 · Three functions hand a co-member exactly what paste 133 Ruling 4 allows, and nothing else:
--      ht29_member_day (task names, sections, planned times, definition of done, check-offs) ·
--      ht29_circle_ratings (the rating NUMBER only - one line reverses it, see the end) ·
--      ht29_join_circle (a join that can be repeated safely and says clearly when a code is wrong).
--  5 · push_subscriptions + nudge_prefs, owner-only. NO SCHEDULE is created here (R70.344: nothing is
--      armed until Cory says "arm"); the schedule is its own file, 2026-09-15_ht29_arm.sql.
--  5b· app_config (read-only for signed-in people): holds the Google sign-in id when there is one.
--  6 · days, day_private and habits join Supabase Realtime, so a phone's check-off reaches the desktop at once.
-- No grant to anon. No row deleted. No column dropped.

create temp table if not exists ht29_before as
  select now() as at, count(*)::int as standards from public.habits;

begin;

-- ---------------------------------------------------------------------------------------------- 0 · backup
create table if not exists public.ht29_policy_backup (
  taken_at   timestamptz not null default now(),
  tablename  text not null,
  policyname text not null,
  permissive text, roles text[], cmd text, qual text, with_check text
);
alter table public.ht29_policy_backup enable row level security;       -- no policy: only the owner reads it
revoke all on public.ht29_policy_backup from anon, authenticated;

insert into public.ht29_policy_backup (tablename, policyname, permissive, roles, cmd, qual, with_check)
select p.tablename, p.policyname, p.permissive, p.roles::text[], p.cmd, p.qual, p.with_check
  from pg_policies p
 where p.schemaname = 'public'
   and p.tablename in ('day_private', 'profile_private', 'habits')
   and p.policyname not like 'ht29\_%'
   and not exists (select 1 from public.ht29_policy_backup);           -- the first run only

-- ------------------------------------------------------------------------ 1 · the three owner-only tables
do $$
declare r record;
begin
  for r in select policyname, tablename from pg_policies
            where schemaname = 'public'
              and tablename in ('day_private', 'profile_private', 'habits')
              and policyname not like 'ht29\_%'
  loop
    execute format('drop policy %I on public.%I', r.policyname, r.tablename);
  end loop;
end $$;

alter table public.day_private     enable row level security;
alter table public.profile_private enable row level security;
alter table public.habits          enable row level security;

drop policy if exists ht29_owner_select on public.day_private;
drop policy if exists ht29_owner_insert on public.day_private;
drop policy if exists ht29_owner_update on public.day_private;
drop policy if exists ht29_owner_delete on public.day_private;
create policy ht29_owner_select on public.day_private for select to authenticated using (user_id = auth.uid());
create policy ht29_owner_insert on public.day_private for insert to authenticated with check (user_id = auth.uid());
create policy ht29_owner_update on public.day_private for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy ht29_owner_delete on public.day_private for delete to authenticated using (user_id = auth.uid());

drop policy if exists ht29_owner_select on public.profile_private;
drop policy if exists ht29_owner_insert on public.profile_private;
drop policy if exists ht29_owner_update on public.profile_private;
drop policy if exists ht29_owner_delete on public.profile_private;
create policy ht29_owner_select on public.profile_private for select to authenticated using (id = auth.uid());
create policy ht29_owner_insert on public.profile_private for insert to authenticated with check (id = auth.uid());
create policy ht29_owner_update on public.profile_private for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy ht29_owner_delete on public.profile_private for delete to authenticated using (id = auth.uid());

drop policy if exists ht29_owner_select on public.habits;
drop policy if exists ht29_owner_insert on public.habits;
drop policy if exists ht29_owner_update on public.habits;
drop policy if exists ht29_owner_delete on public.habits;
create policy ht29_owner_select on public.habits for select to authenticated using (user_id = auth.uid());
create policy ht29_owner_insert on public.habits for insert to authenticated with check (user_id = auth.uid());
create policy ht29_owner_update on public.habits for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy ht29_owner_delete on public.habits for delete to authenticated using (user_id = auth.uid());

-- ---------------------------------------------------------------------------------------- 2 · sections
alter table public.habits add column if not exists section text;
alter table public.habits drop constraint if exists habits_section_ht29;
alter table public.habits add constraint habits_section_ht29
  check (section is null or section in ('morning', 'night', 'standards', 'weekly'));

-- the same rule the app uses to draw TIMED / ANYTIME / WEEKLY today (app.js bucketOf, isSabbathStd)
update public.habits
   set section = case
         when name ~* '^\s*sabbath\y' or group_name ~* '^sabbath$'   then 'night'
         when cadence = 'weekly'                                     then 'weekly'
         when planned_start is not null or time_anchor is not null   then 'morning'
         else 'standards'
       end
 where section is null;

-- ------------------------------------------------------------------------------ 3 · the group, both ways
create or replace function public.ht29_in_circle(c uuid) returns boolean
  language sql stable security definer set search_path = public as
$$ select exists (select 1 from public.circle_members m where m.circle_id = c and m.user_id = auth.uid()) $$;

create or replace function public.ht29_shares_circle(other uuid) returns boolean
  language sql stable security definer set search_path = public as
$$ select other = auth.uid()
       or exists (select 1 from public.circle_members a
                    join public.circle_members b on b.circle_id = a.circle_id
                   where a.user_id = auth.uid() and b.user_id = other) $$;

-- MEASURE BEFORE YOU ENABLE, AND REFUSE RATHER THAN HALF-APPLY.
-- These four get the SELECT policy a co-member needs and nothing else, because their own owner policies are
-- already here. That is only safe if row-level security is ALREADY ON: turn it on for a table that had it off
-- and every write the app makes to that table becomes a silent 0-row statement - Cory's own check-offs first.
-- The rollback could not undo it either: dropping a policy from a table whose RLS this file switched on leaves
-- it locked harder than before. So the state is read, recorded for the undo, and a table with RLS off stops the
-- whole transaction with a message naming it. Nothing is guessed and nothing is half-done.
create table if not exists public.ht29_rls_backup (tablename text primary key, was_enabled boolean not null);
alter table public.ht29_rls_backup enable row level security;          -- no policy: only the owner reads it
revoke all on public.ht29_rls_backup from anon, authenticated;
insert into public.ht29_rls_backup (tablename, was_enabled)
select c.relname, c.relrowsecurity
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
 where n.nspname = 'public'
   and c.relname in ('days', 'profiles', 'circles', 'circle_members', 'day_private', 'profile_private', 'habits')
on conflict (tablename) do nothing;                                    -- the first run's reading is the record

do $$
declare off_list text;
begin
  select string_agg(c.relname, ', ' order by c.relname) into off_list
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and c.relname in ('days', 'profiles', 'circles', 'circle_members')
     and not c.relrowsecurity;
  if off_list is not null then
    raise exception 'STOP - row level security is OFF on: %. This file adds only the co-member SELECT policy '
                    'for those tables, so switching RLS on here would block their own writes. Add the owner '
                    'policies for them first (or tell SPEC), then run this file again. Nothing was changed.',
                    off_list;
  end if;
end $$;

alter table public.days           enable row level security;
alter table public.profiles       enable row level security;
alter table public.circles        enable row level security;
alter table public.circle_members enable row level security;

drop policy if exists ht29_comember_select on public.circle_members;
create policy ht29_comember_select on public.circle_members for select to authenticated
  using (user_id = auth.uid() or public.ht29_in_circle(circle_id));

drop policy if exists ht29_comember_select on public.days;
create policy ht29_comember_select on public.days for select to authenticated
  using (public.ht29_shares_circle(user_id));

drop policy if exists ht29_comember_select on public.profiles;
drop policy if exists ht29_owner_insert on public.profiles;
drop policy if exists ht29_owner_update on public.profiles;
create policy ht29_comember_select on public.profiles for select to authenticated
  using (public.ht29_shares_circle(id));
create policy ht29_owner_insert on public.profiles for insert to authenticated with check (id = auth.uid());
create policy ht29_owner_update on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists ht29_member_select on public.circles;
create policy ht29_member_select on public.circles for select to authenticated
  using (owner_id = auth.uid() or public.ht29_in_circle(id));

-- ------------------------------------------------------------- 4 · what a co-member may see, column by column
create or replace function public.ht29_join_circle(code text) returns uuid
  language plpgsql volatile security definer set search_path = public as
$$
declare cid uuid;
begin
  if auth.uid() is null then
    raise exception 'NOT_SIGNED_IN' using errcode = '28000';
  end if;
  select c.id into cid from public.circles c where upper(c.join_code) = upper(btrim(code)) limit 1;
  if cid is null then
    raise exception 'NO_SUCH_CIRCLE' using errcode = 'P0002';
  end if;
  insert into public.circle_members (circle_id, user_id)
  select cid, auth.uid()
   where not exists (select 1 from public.circle_members m where m.circle_id = cid and m.user_id = auth.uid());
  return cid;
end $$;

create or replace function public.ht29_member_day(member uuid, d date) returns jsonb
  language plpgsql stable security definer set search_path = public as
$$
declare dayrow public.days%rowtype;
        dueset jsonb;
begin
  -- auth.uid() NULL makes ht29_shares_circle() return NULL, and `not NULL` is NULL - which is not TRUE, so the
  -- guard would fall through and hand back the whole day. The grant is revoked from public and anon below, but a
  -- privacy gate must not depend on a grant staying revoked: the caller is named explicitly.
  if auth.uid() is null or member is null or d is null
     or not coalesce(public.ht29_shares_circle(member), false) then
    return null;
  end if;
  select * into dayrow from public.days x where x.user_id = member and x.date = d;
  dueset := coalesce(to_jsonb(dayrow.active_set), '[]'::jsonb);        -- jsonb, json or an array: all read alike
  return jsonb_build_object(
    'user_id', member,
    'date', d,
    'checked', coalesce(to_jsonb(dayrow.checked), '{}'::jsonb),
    'active_set', dueset,
    'pct', dayrow.pct,
    'habits', coalesce((
      select jsonb_agg(jsonb_build_object(
               'id', h.id, 'name', h.name, 'section', h.section, 'group_name', h.group_name,
               'cadence', h.cadence, 'planned_start', h.planned_start, 'planned_end', h.planned_end,
               'time_anchor', h.time_anchor, 'minutes_planned', h.minutes_planned,
               'done_def', h.notes, 'sort_order', h.sort_order, 'active', h.active)
             order by h.sort_order nulls last, h.name)
        from public.habits h
       where h.user_id = member
         and (h.active is true or dueset ? h.id::text)
    ), '[]'::jsonb));
end $$;

create or replace function public.ht29_circle_ratings(d0 date, d1 date)
  returns table (user_id uuid, date date, rating int)
  language sql stable security definer set search_path = public as
$$ select p.user_id, p.date, p.rating::int
     from public.day_private p
    where auth.uid() is not null                    -- named, so the gate never rests on a grant staying revoked
      and p.date between d0 and d1
      and p.rating is not null
      and p.user_id <> auth.uid()
      and coalesce(public.ht29_shares_circle(p.user_id), false) $$;

revoke execute on function public.ht29_in_circle(uuid)            from public, anon;
revoke execute on function public.ht29_shares_circle(uuid)        from public, anon;
revoke execute on function public.ht29_join_circle(text)          from public, anon;
revoke execute on function public.ht29_member_day(uuid, date)     from public, anon;
revoke execute on function public.ht29_circle_ratings(date, date) from public, anon;
grant  execute on function public.ht29_in_circle(uuid)            to authenticated;
grant  execute on function public.ht29_shares_circle(uuid)        to authenticated;
grant  execute on function public.ht29_join_circle(text)          to authenticated;
grant  execute on function public.ht29_member_day(uuid, date)     to authenticated;
grant  execute on function public.ht29_circle_ratings(date, date) to authenticated;

-- ------------------------------------------------------------------------------------------ 5 · nudges
create table if not exists public.push_subscriptions (
  endpoint   text primary key,
  user_id    uuid not null default auth.uid() references auth.users on delete cascade,
  p256dh     text not null,
  auth_key   text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.nudge_prefs (
  user_id    uuid primary key default auth.uid() references auth.users on delete cascade,
  enabled    boolean not null default false,
  noon       time not null default '12:00',
  evening    time not null default '21:00',
  on_sabbath boolean not null default false,
  tz         text not null default 'America/Chicago',
  last_sent  jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.push_subscriptions enable row level security;
alter table public.nudge_prefs        enable row level security;
revoke all on public.push_subscriptions, public.nudge_prefs from anon;
grant select, insert, update, delete on public.push_subscriptions, public.nudge_prefs to authenticated;

drop policy if exists ht29_owner_all on public.push_subscriptions;
drop policy if exists ht29_owner_all on public.nudge_prefs;
create policy ht29_owner_all on public.push_subscriptions for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy ht29_owner_all on public.nudge_prefs for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ------------------------------------------------------------------------------------- 5b · app config
-- Settings the whole app shares and nobody edits from the app: today only `google_client_id`, which turns
-- on "Connect Google Drive" (paste 133 S6.23). A signed-in person may read it; only the owner of the
-- database writes it (the SQL editor, or ht29_unlock.py --google-id). A browser app's client id is public.
create table if not exists public.app_config (
  key        text primary key,
  value      text not null,
  updated_at timestamptz not null default now()
);
alter table public.app_config enable row level security;
revoke all on public.app_config from anon, authenticated;
grant select on public.app_config to authenticated;
drop policy if exists ht29_read on public.app_config;
create policy ht29_read on public.app_config for select to authenticated using (true);

-- ---------------------------------------------------------------------------------------- 6 · realtime
-- A check-off on the phone reaches the open desktop in about a second instead of at the next 30 s pull
-- (paste 133 S7.27). Realtime applies the policies above to every listener, so a person hears only rows
-- they could already read. The app still pulls every 30 s when a channel cannot open.
do $$
declare t text;
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach t in array array['days', 'day_private', 'habits'] loop
      if not exists (select 1 from pg_publication_tables
                      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t) then
        execute format('alter publication supabase_realtime add table public.%I', t);
      end if;
    end loop;
  end if;
end $$;

commit;

-- ----------------------------------------------------------------------- what Run shows you (read only)
-- One row. standards_before = standards_after, or something is wrong - send the screenshot.
select b.standards                                           as standards_before,
       count(h.*)::int                                       as standards_after,
       count(*) filter (where h.section = 'morning')::int    as morning,
       count(*) filter (where h.section = 'night')::int      as night,
       count(*) filter (where h.section = 'standards')::int  as standards,
       count(*) filter (where h.section = 'weekly')::int     as weekly,
       (select count(*)::int from pg_policies p where p.schemaname = 'public'
          and p.tablename = 'day_private' and p.policyname not like 'ht29\_%') as journal_policies_not_owner_only
  from ht29_before b
  left join public.habits h on true
 group by b.standards;

-- AND THE SWITCH ITSELF, printed rather than assumed: every one of these must read true. A table with RLS off
-- is a table anyone with the shipped key can read, and until this grid existed nothing said so out loud.
select c.relname as "table", c.relrowsecurity as "rls on",
       (select b.was_enabled from public.ht29_rls_backup b where b.tablename = c.relname) as "rls before"
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
 where n.nspname = 'public'
   and c.relname in ('day_private', 'profile_private', 'habits', 'days', 'profiles', 'circles', 'circle_members')
 order by 1;

-- ONE LINE REVERSES THE RATING NUMBER (paste 133 Ruling 4 - "Cory reverses in one word"):
--   revoke execute on function public.ht29_circle_ratings(date, date) from authenticated;

-- ============================================================================
-- 2026-09-20_ht30.sql
-- ============================================================================
-- ============================================================================================
-- HT-30 (PASTE 137) . ONE COLUMN, SO A SABBATH FOLLOWS THE PERSON AND NOT THE DEVICE
-- WIRE HT-30 . Sunday 2026-09-20 . run it whole, in Supabase -> SQL Editor -> New query -> Run.
--
-- WHAT IT DOES, AND NOTHING ELSE:
--   profile_private.sabbath_dow smallint null   -- 0 Sunday .. 6 Saturday, NULL = no Sabbath kept
--
-- The app works before and after this runs (it probes the column the way it probes `cue`,
-- `target_age`, `notes` and `section`). Until it exists the choice is kept on the device and
-- Settings says so in one line. Nothing else changes: no policy, no grant, no other table.
--
-- SAFE TO RUN TWICE. One transaction. It REFUSES rather than half-applying if row level security
-- is off on the table it touches - the same contract 2026-09-15_ht29.sql ships with, and for the
-- same reason: a private column on an unprotected table is worse than no column at all.
-- Undo is at the foot of this file, commented out.
-- ============================================================================================

begin;

do $$
begin
  if not exists (select 1 from pg_tables where schemaname = 'public' and tablename = 'profile_private') then
    raise exception 'HT-30: public.profile_private does not exist - run 2026-09-15_ht29.sql first';
  end if;
  if not exists (select 1 from pg_tables
                 where schemaname = 'public' and tablename = 'profile_private' and rowsecurity) then
    raise exception 'HT-30: row level security is OFF on public.profile_private - refusing to add a private column to an unprotected table';
  end if;
end $$;

alter table public.profile_private
  add column if not exists sabbath_dow smallint;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'profile_private_sabbath_dow_ck') then
    alter table public.profile_private
      add constraint profile_private_sabbath_dow_ck
      check (sabbath_dow is null or (sabbath_dow between 0 and 6));
  end if;
end $$;

comment on column public.profile_private.sabbath_dow is
  'HT-30 (Cory 2026-09-20): the day of week this person keeps as a Sabbath, 0=Sunday..6=Saturday. '
  'NULL means none is kept - the default for every account. On that day the list shows the Sabbath '
  'check-off alone; DEC-172''s weight arithmetic is untouched.';

commit;

-- ---- UNDO ----------------------------------------------------------------------------------
-- The column holds one person's answer to one question, so dropping it loses that answer and
-- nothing else; the app falls straight back to keeping it on the device.
--
--   begin;
--   alter table public.profile_private drop constraint if exists profile_private_sabbath_dow_ck;
--   alter table public.profile_private drop column if exists sabbath_dow;
--   commit;

-- ============================================================================
-- 2026-09-22_ht31.sql
-- ============================================================================
-- 2026-09-22_ht31.sql - WIRE HT-31 (paste 143 S6.18 + S7.23): the two things HT-31 needs from the
-- database, and nothing else.
--
-- YOU DO NOT RUN THIS FILE BY ITSELF. Run `tools/sql/ht_pending.sql`, which is 29, then 30, then this,
-- in one paste - so the number of wires that have stacked up never becomes the number of things Cory
-- has to do. This file is kept separate because a wire's own changes should be readable on their own.
--
-- ONE transaction: it applies completely or not at all. SAFE TO RUN TWICE: a second run changes nothing.
-- UNDO: at the foot of this file.
--
-- WHAT CHANGES
--  1 - circles.members_can_invite (boolean, default true). Cory 9/21: "a quick link I or any other user
--      can send". Any member may invite; the group's starter can switch that off. The app reads the
--      column when it exists and behaves as `true` when it does not, so nothing waits for this.
--  2 - ht31_circle_peek(code) -> (name, members). What a person sees BEFORE they agree to join: whose
--      group it is and how many people are in it. TWO COLUMNS, and there is no third - no member names,
--      no ids, no days, nothing of anyone's journal. It answers only for a code the caller already
--      holds, which is the same secret the join itself requires.
-- No grant to anon. No row deleted. No column dropped. No policy on any table is replaced.

begin;

-- 1 ------------------------------------------------------------------------------------------
alter table public.circles add column if not exists members_can_invite boolean not null default true;

comment on column public.circles.members_can_invite is
  'HT-31 (Cory 2026-09-21): any member may send the invite link. The group''s starter can switch it '
  'off in Group settings. The app treats a missing column as true, so the feature never waits on a '
  'migration - this only makes the OFF switch possible.';

-- 2 ------------------------------------------------------------------------------------------
-- SECURITY DEFINER because `circles` is readable only by its members, and the whole point is to answer
-- someone who is NOT one yet. It is safe for exactly the reason the join is safe: the caller must
-- already hold a 128-bit code, and what comes back is a name and a count.
create or replace function public.ht31_circle_peek(code text)
returns table (name text, members integer)
language sql
security definer
set search_path = public
stable
as $$
  select c.name,
         (select count(*)::int from public.circle_members m where m.circle_id = c.id) as members
    from public.circles c
   where c.join_code = upper(btrim(code))
   limit 1;
$$;

revoke all on function public.ht31_circle_peek(text) from public, anon;
grant execute on function public.ht31_circle_peek(text) to authenticated;

commit;

-- WHAT IT LOOKS LIKE AFTERWARDS, printed rather than assumed.
select 'circles.members_can_invite' as thing,
       (select count(*) from information_schema.columns
         where table_schema = 'public' and table_name = 'circles'
           and column_name = 'members_can_invite')::text as present
union all
select 'ht31_circle_peek', (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                             where n.nspname = 'public' and p.proname = 'ht31_circle_peek')::text;

-- ---- UNDO ------------------------------------------------------------------------------------
-- The column holds one group's answer to one question and the function reveals a name and a count;
-- dropping either loses nothing else, and the app falls back to "any member may invite" and to the
-- one quiet line that says the group's name is not available yet.
--
--   begin;
--   drop function if exists public.ht31_circle_peek(text);
--   alter table public.circles drop column if exists members_can_invite;
--   commit;

-- ============================================================================
-- 2026-09-23_ht32.sql
-- ============================================================================
-- 2026-09-23_ht32.sql - WIRE HT-32 (paste 148 + nudges N1-N7).
--
-- Idempotent by construction: every statement is `if not exists` / `or replace`, so running this
-- twice changes nothing. It is appended to `ht_pending.sql` by `tools/sql/build_pending.py`, which
-- puts the whole stack's RLS guard in front of it - so nothing here runs on a database whose row
-- level security is off.
--
-- WHAT IT ADDS, and which part of the paste asked for it:
--   S6.14   profiles.theme                       the picker, across devices
--   N4      profiles.mirror                      where that member's journal mirrors
--   S4.10   circle_members.reward / .consequence the stakes, free text, that member's own
--   N1      stakes_log                           every edit: who, when, before -> after
--   S4.10   profiles.report_hour / .timezone     when a member's day closes, in their zone
--   S4.8    reports                              one row per member per day, and per week
--   S2.4    circle_pending                       a member added by email before they sign in
--   S5.11   (no table)                           the cap rides HT-29's `nudge_prefs.last_sent`
--   N2      supabase_realtime                    the two tables the mirror daemon listens to
--
-- PRIVACY IS STRUCTURAL HERE, NOT A POLICY BOLTED ON (CLAUDE.md, and 143's Ruling 4). `reports`
-- carries a day's NUMBERS and a member's own stakes text, and it has no column that could hold a
-- journal line. The four private fields live in `day_private` and there is no path from this table
-- to them - not a foreign key, not a view, not a function. A report cannot leak what it cannot name.

begin;

-- ---------------------------------------------------------------- S6.14 / N4 . per-person settings
alter table public.profiles            add column if not exists theme text;
alter table public.profiles            add column if not exists mirror text default 'none';
alter table public.profiles            add column if not exists report_hour int;
alter table public.profiles            add column if not exists timezone text;

do $ht32_ck$
begin
  -- A CHECK, NOT AN ENUM. `mirror`'s values live in `standard/shared/mirrors.js` and N4's whole
  -- point is that a new renderer is a line of config - a Postgres enum would make it a migration,
  -- which is the thing N4 says must never be needed again. So the column only refuses nonsense.
  if not exists (select 1 from pg_constraint where conname = 'profiles_report_hour_ck') then
    alter table public.profiles add constraint profiles_report_hour_ck
      check (report_hour is null or (report_hour >= 0 and report_hour <= 23));
  end if;
end
$ht32_ck$;

-- ---------------------------------------------------------------- S4.10 / N1 . the stakes
alter table public.circle_members add column if not exists reward text;
alter table public.circle_members add column if not exists consequence text;

-- N1: "Every edit is logged (who, when, before -> after) and visible on the member's row; the Friday
-- report prints the text in force at week's end." A log is the only way the second half is possible:
-- without it, Friday can only print what the text says TODAY.
create table if not exists public.stakes_log (
  id          bigserial primary key,
  circle_id   uuid not null,
  member_id   uuid not null,
  field       text not null check (field in ('reward', 'consequence')),
  before_text text,
  after_text  text,
  edited_by   uuid not null,
  edited_at   timestamptz not null default now()
);
create index if not exists stakes_log_member_idx on public.stakes_log (member_id, edited_at desc);
alter table public.stakes_log enable row level security;

-- ---------------------------------------------------------------- S4.8 . the reports
create table if not exists public.reports (
  id         bigserial primary key,
  kind       text not null check (kind in ('daily', 'weekly')),
  user_id    uuid not null,
  circle_id  uuid,
  period     date not null,                   -- the day, or the week's Friday
  pct        numeric,                         -- the day's %, or the week's average
  rating     int,                             -- daily only
  streak     int,
  need_next  numeric,                         -- what tomorrow has to be
  state      text,                            -- secured | on-track | at-risk | out-of-reach
  days_met   int,                             -- weekly: days at or above target
  best_day   date,
  worst_day  date,
  outcome    text check (outcome is null or outcome in ('MET', 'MISSED')),
  stakes     text,                            -- the member's own text AS IT STOOD at period end
  compare    text,                            -- one line against the group
  created_at timestamptz not null default now(),
  unique (kind, user_id, period)              -- ONE row per member per period: the job is idempotent
);
create index if not exists reports_period_idx on public.reports (period desc, kind);
alter table public.reports enable row level security;

-- ---------------------------------------------------------------- S2.4 . a member added by email
-- The row exists BEFORE the person does. When that email signs in, `ht32_claim_pending` turns it
-- into a real membership with no further act by anybody - which is what "they appear now" means.
create table if not exists public.circle_pending (
  id         bigserial primary key,
  circle_id  uuid not null,
  email      text not null,
  added_by   uuid not null,
  added_at   timestamptz not null default now(),
  unique (circle_id, email)
);
alter table public.circle_pending enable row level security;

-- ---------------------------------------------------------------- S5.11 . one push a day
-- NO NEW TABLE. `public.push_subscriptions` (HT-29, 2026-09-15_ht29.sql) already holds one endpoint
-- per device and `app.js`'s `subscribe()` already writes to it; `public.nudge_prefs` already holds
-- `last_sent` and `dueSlot` has read it since then. A second `push_subs` table was written here and
-- REMOVED before it existed anywhere: two tables for one device address is the duplication R70.282
-- exists to delete, and the failure mode is the quiet one - the app keeps writing HT-29's table, the
-- new sender reads the new one, and every push goes to nobody with nothing to say so.
--
-- So S5's cap lands in `nudge_prefs.last_sent`, beside the two slots it already caps:
--   last_sent = {"noon": "...", "evening": "...", "report": "2026-09-23"}
-- `report_hour` and `timezone` are on `profiles` above, because they are when a PERSON's day closes -
-- the report row and the push both read them, and two answers to "when does his day end" is the same
-- mistake one layer up.

-- ---------------------------------------------------------------- N2 . the daemon's two ears
do $ht32_rt$
begin
  -- ONE IDEMPOTENT LINE, as N2 asks. `ht_daemon.py --check` names this statement verbatim when it
  -- refuses to start, so nobody has to go looking for it.
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables
                    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'days') then
      alter publication supabase_realtime add table public.days;
    end if;
    if not exists (select 1 from pg_publication_tables
                    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'day_private') then
      alter publication supabase_realtime add table public.day_private;
    end if;
  end if;
end
$ht32_rt$;

commit;

-- ==================================================================================================
-- POLICIES. Separate transaction: a policy that already exists is dropped and recreated, so this
-- block is idempotent in the way `create policy` alone is not.
-- ==================================================================================================
begin;

drop policy if exists ht32_reports_read   on public.reports;
drop policy if exists ht32_reports_owner  on public.reports;
drop policy if exists ht32_stakes_read    on public.stakes_log;
drop policy if exists ht32_pending_read   on public.circle_pending;
drop policy if exists ht32_pending_write  on public.circle_pending;

-- EVERY MEMBER SEES EVERY MEMBER'S ROWS (the 9/15 visibility ruling, S4.9) - but only inside a
-- circle they are themselves in. The subquery is the whole fence.
create policy ht32_reports_read on public.reports for select to authenticated
  using (
    user_id = auth.uid()
    or exists (select 1 from public.circle_members me
                join public.circle_members them on them.circle_id = me.circle_id
               where me.user_id = auth.uid() and them.user_id = public.reports.user_id)
  );
-- WRITES ARE THE JOB'S, NOT THE CLIENT'S (S4.8: "generated by ONE server-side job ... never by the
-- client"). `authenticated` gets no insert or update here at all; the job uses the service key.
create policy ht32_reports_owner on public.reports for all to service_role using (true) with check (true);

create policy ht32_stakes_read on public.stakes_log for select to authenticated
  using (exists (select 1 from public.circle_members me
                  join public.circle_members them on them.circle_id = me.circle_id
                 where me.user_id = auth.uid() and them.user_id = public.stakes_log.member_id));

create policy ht32_pending_read on public.circle_pending for select to authenticated
  using (exists (select 1 from public.circle_members me
                 where me.user_id = auth.uid() and me.circle_id = public.circle_pending.circle_id));
-- "a pending row can be removed by whoever added it" (S2.4), and added by any member of the circle.
create policy ht32_pending_write on public.circle_pending for all to authenticated
  using (added_by = auth.uid())
  with check (exists (select 1 from public.circle_members me
                      where me.user_id = auth.uid() and me.circle_id = public.circle_pending.circle_id));

grant select on public.reports, public.stakes_log, public.circle_pending to authenticated;
grant select, insert, update, delete on public.circle_pending to authenticated;
grant usage, select on sequence public.circle_pending_id_seq to authenticated;

commit;

-- ==================================================================================================
-- THE ONE FUNCTION. A pending row becomes a membership the moment its email signs in - "with no
-- further act" (S2.4). It is SECURITY DEFINER because the person claiming has, by definition, no
-- membership yet and so cannot see the circle; it is narrow to compensate - it acts only on rows
-- whose email equals the CALLER'S OWN verified email, and it can do nothing else.
-- ==================================================================================================
create or replace function public.ht32_claim_pending()
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  mine text;
  n    int := 0;
begin
  select lower(email) into mine from auth.users where id = auth.uid();
  if mine is null then
    return 0;
  end if;
  insert into public.circle_members (circle_id, user_id)
    select p.circle_id, auth.uid() from public.circle_pending p
     where lower(p.email) = mine
       and not exists (select 1 from public.circle_members m
                        where m.circle_id = p.circle_id and m.user_id = auth.uid());
  get diagnostics n = row_count;
  -- IDEMPOTENT BY THE LINK ROUTE TOO (S2.4): joining by invite link fulfils a pending row for the
  -- same email, so the row is cleared whether the membership was made here or by the link.
  delete from public.circle_pending p where lower(p.email) = mine;
  return n;
end;
$$;

revoke all on function public.ht32_claim_pending() from public;
grant execute on function public.ht32_claim_pending() to authenticated;

-- ==================================================================================================
-- THE GRID. One row, and it says whether this file did what it says.
-- ==================================================================================================
select 'ht32 columns'  as thing,
       (select count(*) from information_schema.columns
         where table_schema = 'public' and table_name = 'profiles'
           and column_name in ('theme', 'mirror', 'report_hour', 'timezone'))            as have,
       4                                                                                  as want
union all
select 'ht32 tables',
       (select count(*) from pg_tables where schemaname = 'public'
         and tablename in ('reports', 'stakes_log', 'circle_pending')), 3
union all
select 'ht32 stakes columns',
       (select count(*) from information_schema.columns
         where table_schema = 'public' and table_name = 'circle_members'
           and column_name in ('reward', 'consequence')), 2
union all
select 'ht32 realtime',
       (select count(*) from pg_publication_tables
         where pubname = 'supabase_realtime' and schemaname = 'public'
           and tablename in ('days', 'day_private')), 2
union all
select 'ht32 claim_pending',
       (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
         where n.nspname = 'public' and p.proname = 'ht32_claim_pending'), 1;

-- ------------------------------------------------------------------------------------------------
-- DONE. Everything above is applied. The app notices on its next load; nothing needs a deploy.
